#!/bin/bash

# if <command> ; then ... fi  by check exit code(0 - true, not 0 -i false)
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Not a git repository"
    exit 1
fi

# fix git status messy path
git config --global core.quotepath false

# fix git log messy commit comments
git config --global i18n.commitencoding utf-8
git config --global i18n.logoutputencoding utf-8
